name: Deploy to Docker

on:
  push:
    branches:
      - publish

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
        npm install

    - name: Build Angular application
      run: |
        npm run build --prod

    - name: Archive Docker image
      run: |
        docker build -t shopfrontproduct:latest -f DOCKERFILE .
        docker save shopfrontproduct:latest -o shopfrontproduct.tar

    - name: Transfer image to server
      uses: appleboy/scp-action@v0.1.2
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        source: shopfrontproduct.tar
        target: /home/${{ secrets.SERVER_USER }}/shopfrontproduct.tar

    - name: Load and deploy image on server
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          docker load -i /home/${{ secrets.SERVER_USER }}/shopfrontproduct.tar
          docker stop shopfrontproduct || true
          docker rm shopfrontproduct || true
          docker run -d --name shopfrontproduct -p 8080:80 shopfrontproduct:latest
