name: Deploy to Docker

on:
  push:
    branches:
      - publish

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
        npm install

    - name: Build Angular application
      run: |
        npm run build --prod

    - name: Build Docker image
      run: |
        docker build -t shopfrontproduct:latest .

    - name: Deploy on server
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          docker stop shopfrontproduct || true
          docker rm shopfrontproduct || true
          docker run -d --name shopfrontproduct -p 6985:6985 shopfrontproduct:latest
